# Utility

# git
[[plugins]]
repo = 'mattn/gist-vim'
depends = 'webapi-vim'
on_cmd = ['Gist']

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'gregsexton/gitv'
depends = 'vim-fugitive'
on_cmd = ['Gitv']

# Undo
[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']
hook_post_source = 'nnoremap <Leader>g :GundoToggle<CR>'

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = ['nxo', '<Plug>(quickrun)']
hook_post_source = '''
    nmap <Leader>r <Plug>(quickrun)
    let g:quickrun_config = {
        \ "*": {"runner": "remote/vimproc"},
        \ }
'''

# python

# need pip install jedi
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3', 'djangohtml']
hook_add = '''
        let g:jedi#use_tabs_not_buffers = 1
        let g:jedi#popup_select_first = 0
        let g:jedi#popup_on_dot = 0
        let g:jedi#goto_command = "<leader>d"
        let g:jedi#goto_assignments_command = "<leader>g"
        let g:jedi#goto_definitions_command = ""
        let g:jedi#documentation_command = "K"
        let g:jedi#usages_command = "<leader>n"
        let g:jedi#rename_command = "<leader>R"
        autocmd FileType python setlocal completeopt-=preview
    '''
[[plugins]]
repo = 'ervandew/supertab'

# django
[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'python3', 'djangohtml']

# virtualenv
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', 'python3', 'djangohtml']
